export const GET_ALL_POST = "GET_ALL_POST"
export const GET_ALL_SPECIALITIES = "GET_ALL_SPECIALITIES"
export const GET_ALL_COURSES = "GET_ALL_COURSES"
export const GET_ALL_TEACHERS = "GET_ALL_TEACHERS"

export const GET_SINGLE_POST = "GET_SINGLE_POST"
export const GET_SINGLE_COURSE = "GET_SINGLE_COURSE"
export const GET_SINGLE_SPECIALITY = "GET_SINGLE_SPECIALITY"
export const GET_SINGLE_CLASS = "GET_SINGLE_CLASS"

export const GET_INDEX_LIST = "GET_INDEX_LIST" 
